import type { ModelConfig, ParameterDefinition } from '../types';

// Model configurations
export const MODELS: Record<string, ModelConfig> = {
  't2i': {
    model_id: 'wan2.5-t2i-preview',
    model_name: 'wan2.5-t2i-preview',
    display_name: 'Wan 2.5 Text-to-Image',
    description: 'Generate images from text descriptions with advanced text rendering capabilities',
    api_type: 'async',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis',
    icon: '🎨',
    category: 'image',
  },
  'i2i': {
    model_id: 'wan2.5-i2i-preview',
    model_name: 'wan2.5-i2i-preview',
    display_name: 'Wan 2.5 Image-to-Image',
    description: 'Edit images or fuse multiple images based on text instructions',
    api_type: 'async',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/image2image/image-synthesis',
    icon: '✨',
    category: 'image',
  },
  'i2v': {
    model_id: 'wan2.5-i2v-preview',
    model_name: 'wan2.5-i2v-preview',
    display_name: 'Wan 2.5 Image-to-Video',
    description: 'Create videos from images with optional audio support',
    api_type: 'async',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    icon: '🎬',
    category: 'video',
  },
  'kf2v': {
    model_id: 'wan2.2-kf2v-flash',
    model_name: 'wan2.2-kf2v-flash',
    display_name: 'Wan 2.2 Keyframe-to-Video',
    description: 'Generate smooth transition videos from first and last frame images',
    api_type: 'async',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/image2video/video-synthesis',
    icon: '🎞️',
    category: 'video',
  },
};

// Task query endpoint for async models
export const TASK_QUERY_ENDPOINT = '/api/api/v1/tasks';

// Parameter definitions for each model
export const T2I_PARAMETERS: ParameterDefinition[] = [
  {
    name: 'prompt',
    label: 'Prompt',
    type: 'textarea',
    required: true,
    maxLength: 2000,
    placeholder: 'Describe the image you want to generate...',
    tooltip: 'Text prompt describing the desired image (max 2000 characters for wan2.5-t2i-preview)',
  },
  {
    name: 'negative_prompt',
    label: 'Negative Prompt',
    type: 'text',
    required: false,
    maxLength: 500,
    placeholder: 'Elements to avoid in the image...',
    tooltip: 'Describe what you don\'t want to see in the image (max 500 characters)',
  },
  {
    name: 'size',
    label: 'Image Size',
    type: 'select',
    required: false,
    defaultValue: '1280*1280',
    options: [
      { label: '1280×1280 (1:1)', value: '1280*1280' },
      { label: '1024×1024 (1:1)', value: '1024*1024' },
      { label: '1280×720 (16:9)', value: '1280*720' },
      { label: '720×1280 (9:16)', value: '720*1280' },
      { label: '1200×800 (3:2)', value: '1200*800' },
      { label: '800×1200 (2:3)', value: '800*1200' },
      { label: '1280×960 (4:3)', value: '1280*960' },
      { label: '960×1280 (3:4)', value: '960*1280' },
    ],
    tooltip: 'Resolution and aspect ratio. Total pixels must be between 768×768 and 1440×1440, aspect ratio between 1:4 and 4:1',
  },
  {
    name: 'n',
    label: 'Number of Images',
    type: 'number',
    required: false,
    defaultValue: 1,
    min: 1,
    max: 4,
    tooltip: 'Number of images to generate (1-4). Note: affects pricing',
  },
  {
    name: 'prompt_extend',
    label: 'Intelligent Prompt Enhancement',
    type: 'boolean',
    required: false,
    defaultValue: false,
    tooltip: 'Use AI to automatically improve and expand your prompt (default: false for wan2.5-t2i-preview)',
  },
  {
    name: 'watermark',
    label: 'Add Watermark',
    type: 'boolean',
    required: false,
    defaultValue: false,
    tooltip: 'Add "AI生成" watermark to the image',
  },
  {
    name: 'seed',
    label: 'Random Seed (optional)',
    type: 'number',
    required: false,
    min: 0,
    max: 2147483647,
    placeholder: 'Leave empty for random',
    tooltip: 'Set a seed value for reproducible results',
  },
];

export const I2I_PARAMETERS: ParameterDefinition[] = [
  {
    name: 'images',
    label: 'Upload Images (max 2)',
    type: 'images',
    required: true,
    tooltip: 'Upload 1-2 images for editing or fusion',
  },
  {
    name: 'prompt',
    label: 'Editing Instructions',
    type: 'textarea',
    required: true,
    maxLength: 2000,
    placeholder: 'Describe how to edit or combine the images...',
    tooltip: 'Describe the desired changes or how to combine images (max 2000 characters)',
  },
  {
    name: 'negative_prompt',
    label: 'Negative Prompt',
    type: 'text',
    required: false,
    maxLength: 500,
    placeholder: 'Elements to avoid...',
    tooltip: 'Describe what you don\'t want in the result',
  },
  {
    name: 'n',
    label: 'Number of Results',
    type: 'number',
    required: false,
    defaultValue: 1,
    min: 1,
    max: 4,
    tooltip: 'Number of images to generate (affects cost)',
  },
  {
    name: 'watermark',
    label: 'Add Watermark',
    type: 'boolean',
    required: false,
    defaultValue: false,
    tooltip: 'Add "AI生成" watermark to images',
  },
  {
    name: 'seed',
    label: 'Random Seed (optional)',
    type: 'number',
    required: false,
    min: 0,
    max: 2147483647,
    placeholder: 'Leave empty for random',
    tooltip: 'Set a seed value for reproducible results',
  },
];

export const I2V_PARAMETERS: ParameterDefinition[] = [
  {
    name: 'img_url',
    label: 'First Frame Image',
    type: 'image',
    required: true,
    tooltip: 'Upload the starting image for the video',
  },
  {
    name: 'prompt',
    label: 'Video Description',
    type: 'textarea',
    required: false,
    maxLength: 2000,
    placeholder: 'Describe the motion and content of the video...',
    tooltip: 'Describe the desired video content and motion (max 2000 characters)',
  },
  {
    name: 'audio_url',
    label: 'Custom Audio (optional)',
    type: 'text',
    required: false,
    placeholder: 'https://example.com/audio.mp3',
    tooltip: 'URL to custom audio file for the video',
    showWhen: (formData) => formData.audio === false,
  },
  {
    name: 'negative_prompt',
    label: 'Negative Prompt',
    type: 'text',
    required: false,
    maxLength: 500,
    placeholder: 'Elements to avoid...',
    tooltip: 'Describe what you don\'t want in the video',
  },
  {
    name: 'resolution',
    label: 'Video Resolution',
    type: 'select',
    required: false,
    defaultValue: '480P',
    options: [
      { label: '480P', value: '480P' },
      { label: '720P', value: '720P' },
      { label: '1080P', value: '1080P' },
    ],
    tooltip: 'Resolution quality of the generated video (affects cost)',
  },
  {
    name: 'duration',
    label: 'Video Duration (seconds)',
    type: 'select',
    required: false,
    defaultValue: 10,
    options: [
      { label: '5 seconds', value: 5 },
      { label: '10 seconds', value: 10 },
    ],
    tooltip: 'Length of the generated video',
  },
  {
    name: 'audio',
    label: 'Auto-generate Audio',
    type: 'boolean',
    required: false,
    defaultValue: true,
    tooltip: 'Automatically generate audio for the video',
  },
  {
    name: 'prompt_extend',
    label: 'Intelligent Prompt Enhancement',
    type: 'boolean',
    required: false,
    defaultValue: true,
    tooltip: 'Use AI to automatically improve your prompt',
  },
  {
    name: 'watermark',
    label: 'Add Watermark',
    type: 'boolean',
    required: false,
    defaultValue: false,
    tooltip: 'Add watermark to the video',
  },
  {
    name: 'seed',
    label: 'Random Seed (optional)',
    type: 'number',
    required: false,
    min: 0,
    max: 2147483647,
    placeholder: 'Leave empty for random',
    tooltip: 'Set a seed value for reproducible results',
  },
];

export const KF2V_PARAMETERS: ParameterDefinition[] = [
  {
    name: 'first_frame_url',
    label: 'First Frame Image',
    type: 'image',
    required: true,
    tooltip: 'Upload the starting frame of the video',
  },
  {
    name: 'last_frame_url',
    label: 'Last Frame Image (optional)',
    type: 'image',
    required: false,
    tooltip: 'Upload the ending frame (not needed when using templates)',
  },
  {
    name: 'prompt',
    label: 'Transition Description',
    type: 'textarea',
    required: false,
    maxLength: 800,
    placeholder: 'Describe the motion from first to last frame...',
    tooltip: 'Describe the transition between frames (max 800 characters)',
  },
  {
    name: 'negative_prompt',
    label: 'Negative Prompt',
    type: 'text',
    required: false,
    maxLength: 500,
    placeholder: 'Elements to avoid...',
    tooltip: 'Describe what you don\'t want in the video',
  },
  {
    name: 'resolution',
    label: 'Video Resolution',
    type: 'select',
    required: false,
    defaultValue: '720P',
    options: [
      { label: '480P', value: '480P' },
      { label: '720P', value: '720P' },
      { label: '1080P', value: '1080P' },
    ],
    tooltip: 'Resolution quality of the generated video (affects cost)',
  },
  {
    name: 'template',
    label: 'Special Effect Template (optional)',
    type: 'text',
    required: false,
    placeholder: 'e.g., hanfu-1, flying',
    tooltip: 'Special effect template name for predefined animations',
  },
  {
    name: 'prompt_extend',
    label: 'Intelligent Prompt Enhancement',
    type: 'boolean',
    required: false,
    defaultValue: true,
    tooltip: 'Use AI to automatically improve your prompt',
  },
  {
    name: 'watermark',
    label: 'Add Watermark',
    type: 'boolean',
    required: false,
    defaultValue: false,
    tooltip: 'Add watermark to the video',
  },
  {
    name: 'seed',
    label: 'Random Seed (optional)',
    type: 'number',
    required: false,
    min: 0,
    max: 2147483647,
    placeholder: 'Leave empty for random',
    tooltip: 'Set a seed value for reproducible results',
  },
];

export const MODEL_PARAMETERS: Record<string, ParameterDefinition[]> = {
  't2i': T2I_PARAMETERS,
  'i2i': I2I_PARAMETERS,
  'i2v': I2V_PARAMETERS,
  'kf2v': KF2V_PARAMETERS,
};
